apiVersion: apps/v1
kind: Deployment
metadata:
  name: woker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec: 
      containers:
        - name: multi-docker-worker
          image: ronaldreeggan/multi-docker-worker
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'